Repository CS2103-AY1819S2-W15-3/main, pull requests merged in 2019-03, with the labels that each got.

#63 Add Field "Race"
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Race.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/RaceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.Enhancement

#74 #73 Update User Guide #73
  docs/UserGuide.adoc
Labels: type.Documentation

#76 Add ImportResumesCommand and Update UserGuide #73 #75
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ImportResumesCommand.java
Labels: type.Enhancement

#85 #81 V1.0 Add Person Fields: NRIC, Grade, Gender, InterviewScores, Job…
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/InterviewScores.java
  src/main/java/seedu/address/model/person/JobsApply.java
  src/main/java/seedu/address/model/person/KnownProgLang.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueNricMap.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedJobsApply.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/model/person/InterviewScoresTest.java
  src/test/java/seedu/address/model/person/JobsApplyTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RaceTest.java
  src/test/java/seedu/address/model/person/UniqueNricMapTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.Enhancement

#93 #91 #92 #94 Create Interviews, GenerateInterviewsCommand and update UserGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GenerateInterviewsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interviews/Interviews.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#110 #106 Update User Guide and Developer Guide for Analytics Class
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/resources/view/AnalyticsWindow.fxml
Labels: type.Documentation

#116 #114 #115 Update Interviews and its Commands
  src/main/java/seedu/address/logic/commands/ClearInterviewsCommand.java
  src/main/java/seedu/address/logic/commands/GenerateInterviewsCommand.java
  src/main/java/seedu/address/logic/commands/SetMaxInterviewsADayCommand.java
  src/main/java/seedu/address/logic/commands/ShowInterviewsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetMaxInterviewsADayCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/interviews/Interviews.java
  src/main/java/seedu/address/model/interviews/exceptions/InterviewsPresentException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateJobCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.2, type.Story

#121 #107 Convert analytics results from text to charts
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/analytics/Analytics.java
  src/main/java/seedu/address/ui/AnalyticsWindow.java
  src/main/resources/view/AnalyticsChart.fxml
  src/main/resources/view/AnalyticsWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateJobCommandTest.java
Labels: priority.2, type.Enhancement, type.Story
