Repository CS2103-AY1819S2-W15-3/main, pull requests merged in 2019-04, with the labels that each got.

#126 Update DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#130 #125 #128 #129 Update Interviews and Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenerateInterviewsDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/GenerateInterviewsDiagram.png
  docs/images/InterviewsAssociationClass.png
  docs/images/ModelClassDiagram.png
  docs/team/WeeSooJun.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SetBlockOutDatesCommand.java
  src/main/java/seedu/address/logic/commands/ShowInterviewsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetBlockOutDatesCommandParser.java
  src/main/java/seedu/address/logic/parser/SetMaxInterviewsADayCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interviews/Interviews.java
  src/main/java/seedu/address/ui/InterviewsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/InterviewsWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearInterviewsCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateJobCommandTest.java
  src/test/java/seedu/address/model/interviews/InterviewsTest.java
Labels: priority.2, type.Documentation, type.Enhancement

#145 Fix analytics UI
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/ui/AnalyticsWindow.java
  src/main/resources/view/AnalyticsChart.fxml
Labels: priority.4, type.Enhancement

#200 #105 #197 #198 #199 UI for Job, display all, filter. Analytics for 4 list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CreateJobCommand.java
  src/main/java/seedu/address/logic/commands/DisplayJobCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/GenerateAnalyticsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AnalyticsCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/JobListName.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/main/java/seedu/address/ui/JobCard.java
  src/main/java/seedu/address/ui/JobListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Broom.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/JobListCard.fxml
  src/main/resources/view/MainJobWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/displayAllScene.fxml
  src/main/resources/view/displayJobScene.fxml
  src/main/resources/view/jobDisplayWindow.fxml
Labels: priority.2, type.Enhancement

#205 #204 Make Interviews and delete Person compatible
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/interviews/Interviews.java
Labels: priority.2

#225 Fix create job
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateJobCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFilterCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bugfix

#227 Fix System Tests
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.Bugfix

#251 Add Filter Command System Test
  docs/UserGuide.adoc
  docs/team/danieldssim.adoc
  src/main/java/seedu/address/logic/commands/ClearFilterCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFilterCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFilterCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FilterCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.4

#247 #108 Add Analytics Tests
  docs/UserGuide.adoc
  docs/images/DisplayJob.png
  docs/images/Ui.png
  docs/team/chiuyuhua.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/analytics/Analytics.java
  src/main/java/seedu/address/ui/AnalyticsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/GenerateAnalyticsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AnalyticsCommandParserTest.java
  src/test/java/seedu/address/model/analytics/AnalyticsTest.java
Labels: priority.3

#257 Update UG
  docs/UserGuide.adoc
Labels: type.Documentation

#253 #254 #255 Update Test for ParserUtil for Interviews
  docs/team/WeeSooJun.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/interviews/InterviewsTest.java
Labels: priority.2

#268 #255 #267
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/team/WeeSooJun.adoc
  src/main/java/seedu/address/logic/commands/GenerateAnalyticsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.2, type.Documentation

#270 #267 #255 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DeletePersonInterviewsDiagram.pptx
  docs/images/InterviewsDeletePersonSequenceDiagram.png
  docs/team/WeeSooJun.adoc
Labels: type.Documentation
